### ISSUE TITLE
Create a Data Visualization Feature

### ISSUE THREAD

**Issue by max-torch** [Pazitos10/time-tracker#4]
It would be great if the app had the capability of visually representing the time tracking data. I implemented this feature in Pull Request #3

**Comment by Pazitos10** [comment]
@max-torch Thank you so much for your contributions to the app, it looks amazing!. Unfortunately I couldn't comment on your PR before, sorry about that. I'm merging the code right now.

**Comment by Pazitos10** [comment]
@max-torch could you please update the `README.md` to include the new features?

**Comment by max-torch** [comment]
> @max-torch could you please update `README.md` to include the new features?

Thank you for adopting my code! I will edit the readme soon. By the way, this app is one of the first entries in the first page that comes up in the Google search for "python time tracker". I wonder why or how you were able to accomplish that?

**Comment by Pazitos10** [comment]
> Thank you for adopting my code! I will edit the readme soon. By the way, this app is one of the first entries in the first page that comes up in the Google search for "python time tracker". I wonder why or how you were able to accomplish that?

Really? I had no idea :) ... I guess it's just luck. Thanks for letting me know!

**Comment by max-torch** [comment]
The README is now updated. See PR #5
